### ISSUE TITLE
please change your project name, it's already taken for something very similar

### ISSUE THREAD

**Issue by stef** [bitmand/utterson#19] opened 2016-01-16 16:35 UTC
utterson is indeed a static blog engine for 7 years now: https://github.com/stef/utterson
thanks for your kind cooperation.

**Comment by xxdesmus** [comment] 2016-01-23 03:11
Yeah... seems like it's just really bad form to steal an existing project's name.

**Comment by bitmand** [comment] 2016-01-25 10:05
Sorry for not getting back to you sooner, I really wanted to dedicate time to write a proper response to this issue. First off, I'm marking this as a won't fix for now, but please hear me out before you gather pitchfork and torches.

The main reason for this, is my already very limited time to work on this project. I barely have enough time to keep development running and simply don't have the time to do a full rename of the project again ( yes, it has already been renamed once ).

Secondly, Utterson is an extreme generic name, have you tried searching for 'github utterson'? There is tons of other projects called Utterson and some of them is almost the same as @stef project ( static site generator ) - just a couple of examples:
- pepijndevos/utterson - A static site generator written in Clojure in the style of Jekyll & Hyde.
- alexander-heimbuch/utterson - Simple static blog (and page) generator written in NodeJS.
- zellio/utterson - Light CMS for Jekyll file management.

This project it not a static site generator. It is a web admin/backend interface for Jekyll, which indeed is a static site generator, but this project is not - and newer will be.

I'm really sorry if you think that I "stole" your project name, that was not the intention. I haven't even heard of you project until this issue was created. I did what I'm guessing everyone else did when building stuff around Jekyll, browsed the Wikipedia page for Jekyll & Hyde and picked a random character name.

I have no feeling or speciel intentions with the name Utterson ( other that it's in the family of Jekyll names because of the novel ). I'm really sorry you think I stole the name and/or offended you, that was never my intention.

**Closed as completed** 2016-01-25 10:05 UTC
Labels: wontfix

**Comment by stef** [comment] 2016-01-25 10:12
yeah, i saw that others also reused that name after me. very stupid. what's more, i also found other names of my projects that have been stolen/reused. i have no idea what to do now with all these impostors. thanks for your extensive response though, much appreciated, even if you don't do a rename. would you accept a PR doing the rename btw?

**Comment by bitmand** [comment] 2016-01-27 11:08
The problem is that although the code change is trivial ( besides that it takes a bit of time ), there is a lot of other changes for repository name, url, the website/documentation, people that might have checkouts links to this repo etc. - and also find another name that works - and possible unique :/

I'm certainly not the first to use the name Utterson and my guestimate would be that I definitely won't be the last either. I'm sorry you feel offended, that really was never my intention, but I really don't have the time to do a full name change again :(

Can I help in any other way somehow?
